Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -36,6 +36,21 @@ jobs:
 
       - name: Install dependencies
         uses: r-lib/actions/setup-r-dependencies@v2
+        
+      - name: Run the script
+        run: |
+          #!/bin/bash
+  
+          # Search TODO/FIXME and strip whitespace
+          count=$(grep -Rniwo --include="*.qmd" -e 'TODO\|FIXME' book/ | wc -l)
+          count=$(echo "$count" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
+  
+          # Warn if count>0
+          if [ "$count" -gt 0 ]; then
+              echo "There are $count FIXMEs/TODOs."
+              exit 1 # Exit with a non-zero status code to indicate a warning
+          fi
+        shell: bash
 
       - name: Render book
         run: make render
